config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :users

  root "store#index" , as: 'store'

  post '/line_items/:product_id', to: 'line_items#create', as: :line_items
  delete '/line_items/:id', to: 'line_items#destroy', as: :destroy_line_item

  get '/carts/:id', to: 'carts#show', as: :cart
  delete '/carts/:id', to: 'carts#destroy', as: :destroy_cart

  resources :users do
    member do
      get 'display'
    end
  end

  scope module: :admin do
    resources :posts, :comments
  end

  resources :products do
    collection do
      get 'search'
      post 'outofstock'
    end
  end

  resources :orders do
    resources :products
    member do
      get 'status'
      get 'last_edited'
    end
  end

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  self.primary_key = 'id'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id, product_price)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(
        product_id: product_id,
        price: product_price)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  #self.primary_key='year'
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order
  validates :cart, :product, presence: true
  # validates :product_id, presence: true
  # validates :cart_id, presence:true

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  # has_many :products, inverse_of: :order
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  # validates :name, :address, :email, presence: true
  # validates :pay_type, inclusion: PAYMENT_TYPES
  # validates :order_date, presence: true
  # validates :mobile, :phone, presence: true, numericality: { only_integer: true}, length: { is:10 }
  # validate :phone_and_mobile_cant_be_same
  # validates_associated :products

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def self.by_name(name)
    Order.where("name = ?", name)
  end

  def self.by_email(email)
    Order.where("email = ?", email)
  end


  private

  # def phone_and_mobile_cant_be_same
  #   if mobile == phone
  #     errors[:phone] << "mobile and phone can't be same"
  #   end
  # end

end

app/models/product.rb
class Product < ActiveRecord::Base
  # belongs_to :order, dependent: :destroy
  has_many :line_items
  has_many :orders, through: :line_items
  validates :title, presence: true, uniqueness: { case_sensitive: false}
  validates :price, presence: true, numericality: { greater_than: 0.0}
  validates :description, presence: true
  validates :img_url, allow_blank: true, format: { with: /\w+.[jpg|jpeg|png|gif]/, message: "file must of type jpeg, gif or png format"}
  before_destroy :ensure_not_referenced_by_any_line_item

  def self.latest
    order(:updated_at).last
  end

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class GoodnessValidator < ActiveModel::Validator
  def validate(record)
    if options[:fields].any?{|field| record.send(field) == "Evil" }
      record.errors[:base] << "This person is evil"
    end
  end
end



class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
  validates_with GoodnessValidator, fields: [:name]

private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def show
     @my_cart = Cart.find(params[:id])
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    session[:counter] = 0
    redirect_to store_url
  end

  private

    def set_cart
      @cart = Cart.find(params[:id])
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  skip_before_action :authorize
  before_action :set_cart, only: [:index]

  def index
    @products=Product.order(:title)
    if session[:counter].nil?
      session[:counter] = 1
    else
      session[:counter] += 1
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %><br>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Product Store" %>
    <span id="counter">
    <% if (session[:counter]) && (session[:counter] > 5) %>
    <%= pluralize(session[:counter],"time") %> visited
    <% end %>
    </span>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>
      <ul>
        <li><a href="http://www.kiprosh.com">Home</a></li>
        <li><a href="http://www.google.com">Questions</a></li>
        <li><a href="http://www.google.com">News</a></li>
        <li><a href="http://www.kiprosh.com/careers">Contact</a></li>
      </ul>
      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Store', store_path %></li>
        </ul>
        <br>
        <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
</body>
</html>

app/views/order_notifier/received.html.erb
<h1>OrderNotifier#received</h1>

<p>
  <%= @greeting %>
</p>

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from The Pragmatic Store.
You ordered the following items:
<%= render @order.line_items -%>
We'll send you a separate e-mail when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>Pragmatic Order Shipped</h3>
<p>
This is just to let you know that we've shipped your recent order:
</p>
<table>
<tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items -%>
</table>

app/views/order_notifier/shipped.text.erb
<%= @greeting %>